name: Timers Nuget

on:
  push:
    paths:
      - 'timers/dotnet/lib/**'
      - '.github/workflows/timers-nuget.yml'
  workflow_dispatch:

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: timers/dotnet/lib/Backi.Timers
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}