name: Timediatr Nuget

on:
  push:
    paths:
      - 'mediator/dotnet/timediatr/**'
      - '.github/workflows/timediatr-nuget.yml'
  workflow_dispatch:

jobs:
  publish:
    name: Pack & Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: mediator/dotnet/timediatr/Backi.Timediatr
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}